<?php
 $title = 'Users';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>

 </p>

 <table class="display" id="example">
 <thead> 
 <tr>
     <th>First Name</th>
     <th>Last Name</th>
	 <th>City </th>
	 <th>E-Mail</th>
	 
     <th>&nbsp;</th>
 </tr>
 </thead>
 <tbody>
 <?php foreach ($users as $user) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($user->firstname);?> </td>
     <td><?php echo $this->escapeHtml($user->lastname);?></td>
	 <td><?php echo $this->escapeHtml($user->city);?></td>
	 <td><?php echo $this->escapeHtml($user->email);?></td>
  
      <td>
        
      
 </tr>

 <?php endforeach; ?>
  </tbody>
 </table>
