<?php
$title = 'Pharmacies';
 $this->headTitle($title);
 ?>
 <body class = "admin-page">
 <div class="page-header" role="navigation">
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 </div>


 <p>

 <a class ="add btn btn-primary" href="<?php echo $this->url('admin/index4',
              array('controller' => 'index','action'=>'pharmacyDetail'));?>"> Add Pharmacy </a>

 </p>
 <table class="display" id="example">
 
 <thead> 
 <tr>
     <th>Name</th>
     <th>Address</th>
	 <th>Website</th>
	 <th>&nbsp </th>
	
 </tr>
 </thead>
 <tbody>

 <?php foreach ($pharmacies as $pharmacy) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($pharmacy->name);?> </td>
     <td><?php echo $this->escapeHtml($pharmacy->address);?></td>
	
	 <td><?php echo $this->escapeHtml($pharmacy->website);?></td>
	  <td>
       <a class=" ed btn btn-warning dropdown-toggle" href="<?php echo $this->url('admin/index4',
           array('controller' => 'index','action'=>'pharmacyDetail', 'id' => $pharmacy->getId()));?>">Edit Pharmacy</a>
    	<form class ="del1" method="post" action="<?php echo $this->url('admin/index4',
              array('controller' => 'index','action'=>'deletePharmacy','id' => $pharmacy->getId()));?>" >
    	 <input style ="padding: 3px 38px;"class="del btn btn-danger dropdown-toggle" type="submit" value="Delete">
    	 
     	</form>
      </td>
        
	
        
      
 </tr>

 <?php endforeach; ?>
  </tbody>
 </table>
 </body>
