 <div class="page-header" role="navigation">
 <?php
	 $title = 'Add new Pharmacy';
	 $this->headTitle($title);
 ?>
   <h1><?php echo $this->escapeHtml($title); ?></h1>
 </div>

  <?php $form->prepare();  ?>
  
  <?php 
	  echo $this->form()->openTag($form);
	  echo $this->formHidden($form->get('id_farmacie'));
	?>
   <div class="form-group">
   <?php
      echo $this->formRow($form->get('id_farmacie'));
	  echo $this->formRow($form->get('name'));
	  echo $this->formRow($form->get('password'));
  ?>

  </div>
  <div class="form-group">
  <?php 
	  echo $this->formRow($form->get('country'));
	  echo $this->formRow($form->get('city'));
	?>
  </div>
  <div class="form-group">
  <?php 
	  echo $this->formRow($form->get('street'));
	  echo $this->formRow($form->get('streetnumber'));
  ?>
  </div>
  <div class="form-group">
  <?php 
      echo $this->formRow($form->get('email'));
	  echo $this->formRow($form->get('website'));
	 
  ?>
  </div>
   <div class="form-group">
  <?php 
     
	  echo $this->formSubmit($form->get('submit'));
	  echo $this->form()->closeTag();
  ?>
  </div>
   <div id="panel">
      <input id="latlng" type="text" value="40.714224,-73.961452">
      <input type="button" value="Reverse Geocode" onclick="codeLatLng()">
    </div>
  <div id="map-canvas"></div>
