<h1>View from Client</h1>
<div> Set your address! This will be helpful for finding the nearest pharmacy!</div>
	<?php $form->prepare();  ?>
  
  	<?php 
	  echo $this->form()->openTag($form);
	  echo $this->formHidden($form->get('id'));
	?>
   <div class="form-group">
   <?php
      echo $this->formHidden($form->get('id'));
	  echo $this->formRow($form->get('address'));
	  echo $this->formRow($form->get('dateofbirth'));
	  echo $this->formRow($form->get('firstnamedoctor'));
	  echo $this->formRow($form->get('lastnamedoctor'));
	?>
   </div>
	   <?php 
	  echo $this->formSubmit($form->get('submit'));
	  echo $this->form()->closeTag();
     ?>