 <?php

 $title = 'Add new user';
 $this->headTitle($title);
 ?>
  <h1><?php echo $this->escapeHtml($title); ?></h1>
  <?php
  $form->setAttribute('action', $this->url('client', array('action' => 'add')));
  //var_dump($this->url);
  $form->prepare();
 
  echo $this->form()->openTag($form);
  echo $this->formHidden($form->get('id'));
  echo $this->formRow($form->get('username'));
  echo $this->formRow($form->get('password'));
  echo $this->formRow($form->get('firstname'));
  echo $this->formRow($form->get('lastname'));
  echo $this->formRow($form->get('country'));
  echo $this->formRow($form->get('email'));
  echo $this->formRow($form->get('city'));
  echo $this->formSubmit($form->get('submit'));
  echo $this->form()->closeTag();