 <div class="page-header" role="navigation">
 <?php
	 $title = 'Register as a new user';
	 $this->headTitle($title);
 ?>
   <h1><?php echo $this->escapeHtml($title); ?></h1>
 </div>

  <?php $form->prepare();  ?>
  
  <?php 
	  echo $this->form()->openTag($form);
	  echo $this->formHidden($form->get('id'));
	?>
   <div class="form-group">
   <?php
      echo $this->formHidden($form->get('id'));
	  echo $this->formRow($form->get('username'));
	  echo $this->formRow($form->get('password'));
  ?>
  </div>
  <div class="form-group">
  <?php 
	  echo $this->formRow($form->get('firstname'));
	  echo $this->formRow($form->get('lastname'));
  ?>
  </div>
  <div class="form-group">
  <?php 
	  echo $this->formRow($form->get('country'));
	  echo $this->formRow($form->get('city'));
	 
   ?>
  </div>
  <div class="form-group">
  <?php 
      echo $this->formRow($form->get('email'));
   ?>
  </div>
  <div class="form-group">
  <?php 
	  echo $this->formSubmit($form->get('submit'));
	  echo $this->form()->closeTag();
  ?>
  </div>
 