
<?php

//echo $this->formRow($form->get('drugname'));
?>


<?php
$title = 'Medicines';
 $this->headTitle($title);
 ?>

 <h1><?php echo $this->escapeHtml($title); ?></h1>
 


 <p>


 <table class="display" id="example">
 
 <thead> 
 <tr>
     <th>Name</th>
     <th>Active Ingredient</th>
	 <th>Producer</th>
	 <th>Therapeutic Action</th>
     
 </tr>
 </thead>
 <tbody>

 <?php foreach ($drugs as $drug) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($drug->name);?> </td>
     <td><?php echo $this->escapeHtml($drug->activeingredient);?></td>
     <td><?php echo $this->escapeHtml($drug->producer);?></td>
	 <td><?php echo $this->escapeHtml($drug->therapeutic_action);?>
	 <!--  
       <a class=" ed btn btn-warning dropdown-toggle" href="< php// echo $this->url('admin/index4',
          // array('controller' => 'index','action'=>'detail', 'id' => $user->id));?>">View pharmacies</a>
    -->
      </td>
        
      
 </tr>

 <?php endforeach; ?>
  </tbody>
 </table>
 </body>