<?php
$title = 'Prescriptions';
 $this->headTitle($title);
 ?>

 <div class="page-header" role="navigation">
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 </div>
 <?php $i = 0;?>
  <?php foreach ($prescriptions as $p) : ?>
 <table class="display" >
 <h2><?php $i++; echo "Prescription No." ." " . $i; ?></h2>
 <h4><?php echo "Diagnostic:". " " .$p->getDiagnostic();?></h4>
 <thead> 
 <tr>
     <th>Meds:</th>
     

 </tr>
 </thead>
 <tbody>


  <?php 
       $drugs = $p->getDrugs();
       foreach($drugs as $drug):
?>
 <tr>
     <td><?php echo $this->escapeHtml($drug->getName());?> </td>
         <?php $pharmacy = $drug->getPharmacy();?> 
         <?php foreach ($pharmacy as $pharma) :?>
     <td><b><?php echo "     " . " Available at ". " " .$this->escapeHtml($pharma->getName())."; ". "Price: ". $drug->getPrice(). "lei";?></b> </td>
</tr>


   <?php endforeach; ?>
  <?php endforeach; ?>
  </tbody>
 </table>
 <?php endforeach; ?>
 </body>