<?php
$title = 'Doctors';
$this->headTitle($title);
 ?>
 <body class = "admin-page">
 <div class="page-header" role="navigation">
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 </div>



 <table class="display" id="example">
 
 <thead> 
 <tr>
     <th>First Name</th>
     <th>Last Name</th>
	 <th>City </th>
	 <th>E-Mail</th>
	 <th>Specialization<th>
	 <th>&nbsp</th>
  
 </tr>
 </thead>
 <tbody>

 <?php foreach ($doctors as $doctor) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($doctor->firstname);?> </td>
     <td><?php echo $this->escapeHtml($doctor->lastname);?></td>
	 <td><?php echo $this->escapeHtml($doctor->city);?></td>
	 <td><?php echo $this->escapeHtml($doctor->email);?></td>
	 <td><?php echo $this->escapeHtml($doctor->specializare);?><td>
     <td>
         <a style="min-width: 150px; margin: 0 auto;" class=" ed btn btn-warning dropdown-toggle" href="<?php echo $this->url('doctor/index1',
          array('controller' => 'index', 'action'=>'seedetail', 'id'=>$doctor->getId())); ?>">See Detail</a>
        </td>
 </tr>

 <?php endforeach; ?>
  </tbody>
 </table>
 </body>
