<?php
$title = 'Doctors';
$this->headTitle($title);
 ?>
 <body class = "admin-page">
 <div class="page-header" role="navigation">
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 </div>



 <table class="display" id="example">
 
 <thead> 
 <tr>
     <th>First Name</th>
     <th>Last Name</th>
	 <th>City </th>
	 <th>E-Mail</th>
	 <th>Specialization<th>
  
 </tr>
 </thead>
 <tbody>

 <?php foreach ($doctors as $doctor) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($doctor->firstname);?> </td>
     <td><?php echo $this->escapeHtml($doctor->lastname);?></td>
	 <td><?php echo $this->escapeHtml($doctor->city);?></td>
	 <td><?php echo $this->escapeHtml($doctor->email);?></td>
	 <td><?php echo $this->escapeHtml($doctor->specializare);?><td>

        
      
 </tr>

 <?php endforeach; ?>
  </tbody>
 </table>
 </body>
