
<?php
 $title = 'Medicines';
 $this->headTitle($title);
 ?>

 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <table class="display" id="example">
 <thead> 
 <tr>
     <th>Name</th>
     <th>Active Ingredient</th>
	 <th>Producer</th>
	 <th>Therapeutic Action</th>
</tr>
 </thead>
 <tbody>

 <?php foreach ($drugs as $drug) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($drug->name);?> </td>
     <td><?php echo $this->escapeHtml($drug->activeingredient);?></td>
     <td><?php echo $this->escapeHtml($drug->producer);?></td>
	 <td><p style ="min-width: 150px";><?php echo $this->escapeHtml($drug->therapeutic_action); ?></p>
	 
       <a style="min-width: 150px; margin: 0 auto;" class=" ed btn btn-warning dropdown-toggle" href="<?php echo $this->url('pharmacy/index2',
          array('controller' => 'index', 'action'=>'seedetail', 'idpharma'=> $drug->getId())); ?>">See Detail</a>
   
      </td>     
 </tr>

 <?php endforeach; ?>
  </tbody>
 </table>
 </body>