 <a class=" ed btn btn-warning dropdown-toggle" href="<?php echo $this->url('client/index3',
           array('controller' => 'index','action'=>'findpharmacy', 'id'=>$id));?>"> Find the nearest Pharmacy</a>
 <a class=" ed btn btn-warning dropdown-toggle" href="<?php echo $this->url('client/index3',
           array('controller' => 'index','action'=>'seeprescriptions', 'id'=>$id));?>"> See your prescriptions</a>
 <a class=" ed btn btn-warning dropdown-toggle" href="<?php echo $this->url('client/index3',
           array('controller' => 'index','action'=>'findmeds', 'id'=>$id));?>"> Find meds</a>