<style>
body{
 background: url("../../../img/2-min.jpg");
 background-size:cover;
}
</style>
<body>
 <div class="page-header" role="navigation">
 <?php
	 $title = 'Add new Medicine';
	 $this->headTitle($title);
 ?>
   <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 
  <?php $form->prepare();  ?>
  
  <?php 
	  echo $this->form()->openTag($form);
	  echo $this->formHidden($form->get('id'));
	?>
   <div class="form-group">
   <?php
      echo $this->formRow($form->get('id'));
	  echo $this->formRow($form->get('name'));
	  echo $this->formRow($form->get('activeingredient'));
  ?>

  </div>
  <div class="form-group">
  <?php 
	  echo $this->formRow($form->get('producer'));
	  echo $this->formRow($form->get('therapeutic_action'));
	?>
  </div>
  <div class="form-group">
  <?php 
  	  echo $this->formRow($form->get('cod_atc'));
  	  echo $this->formRow($form->get('price'));
      echo $this->formRow($form->get('leaflet'));
    
	 
  ?>
  </div>

   <div class="form-group">
  <?php 
     
	  echo $this->formSubmit($form->get('submit'));
	  echo $this->form()->closeTag();
  ?>
  </div>
  </div>
  </body>