<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        
       
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/TablesStyle/demo.css'))
                        ->prependStylesheet($this->basePath('css/TablesStyle/shCore.css'))
                        ->prependStylesheet($this->basePath('css/TablesStyle/jquery.dataTables.css'))
                       
                        

        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
        
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            //->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/demo.js'))
            ->prependFile($this->basePath('js/shCore.js'))
            ->prependFile($this->basePath('js/jquery.dataTables.js'))
            ->prependFile($this->basePath('js/jquery.js'))
           
            
            
           // , 'text/javascript', array('conditional' => 'lt IE 9',))
           // ->prependFile($this->basePath('js/jquery.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
           
            
        ; ?>
        <script type="text/javascript" class="init">
         jQuery(document).ready(function() {
            jQuery('#example').DataTable();
        } );
       </script>
       <script src="https://maps.googleapis.com/maps/api/js?v=3.exp/AIzaSyDtxyFEN3DxkVQrbbpMyilWZWsy6dH39ac"></script>
       
    <script type="text/javascript">

    var map;
    var geocoder;
    var infowindow = new google.maps.InfoWindow();
    var marker;
    
    function initialize() {
      map = new google.maps.Map(document.getElementById('map-canvas'), {
        zoom: 8,
        center: {lat: 44.4313, lng: 26.1253}
      });
      var latlng = new google.maps.LatLng(40.730885,-73.997383);
      geocoder = new google.maps.Geocoder();
    }
    
    function codeAddress() {
        var address = document.getElementById("address").value;
        address += " " +document.getElementById('city').value;
        address += " " +document.getElementById('street').value;
        address += " " +document.getElementById('streetnumber').value;
        geocoder.geocode( { 'address': address}, function(results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            map.setCenter(results[0].geometry.location);
            var marker = new google.maps.Marker({
                map: map,
                draggable: true,
                position: results[0].geometry.location
            });
           
            google.maps.event.addListener(marker, 'dragend', function(evt){
         	   document.getElementById('latlng').value = evt.latLng.lat().toFixed(3) + ',' + evt.latLng.lng().toFixed(3);
         	   });

         	 

         	   google.maps.event.addListener(marker, 'dragend', function(evt){
         	   document.getElementById('latlng').value = results[1].formatted_address;
         
         	   });
         	   
         	  map.setCenter(marker.position);
         	  marker.setMap(map);



         	
                
          } else {
            alert("Geocode was not successful for the following reason: " + status );
          }
        });
      }
   
    function codeLatLng() {
    	  var input = document.getElementById('latlng').value;
    	  var latlngStr = input.split(',', 2);
    	  var lat = parseFloat(latlngStr[0]);
    	  var lng = parseFloat(latlngStr[1]);
    	  var latlng = new google.maps.LatLng(lat, lng);
    	  geocoder.geocode({'latLng': latlng}, function(results, status) {
    	    if (status == google.maps.GeocoderStatus.OK) {
    	      if (results[1]) {
    	        map.setZoom(11);
    	        marker = new google.maps.Marker({
    	            position: latlng,
    	            map: map
    	        });
    	        marker.setMap(map);
    	        document.getElementById('city').value = results[1].formatted_address;
    	        infowindow.setContent(results[1].formatted_address);
    	        infowindow.open(map, marker);
    	      } else {
    	        alert('No results found');
    	      }
    	    } else {
    	      alert('Geocoder failed due to: ' + status);
    	    }
    	  });
    	}
   
	
    google.maps.event.addDomListener(window, 'load', initialize);
    
    </script>
    <script>
    
    document.addEventListener('DOMContentLoaded', function () {
    	var el =document.getElementById("email");
        el.addEventListener("click", codeAddress);
        
    });
    function geocodePosition(pos) {
    	  geocoder.geocode({
    	    latLng: pos
    	  }, function(responses) {
    	    if (responses && responses.length > 0) {
    	      updateMarkerAddress(responses[0].formatted_address);
    	    } else {
    	      updateMarkerAddress('Cannot determine address at this location.');
    	    }
    	  });
    	}
    google.maps.event.addListener(marker, 'dragend', function() {
        updateMarkerStatus('Drag ended');
        geocodePosition(marker.getPosition());
      });
    
    </script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
              </div> <!-- /container -->
            <hr>
            <div>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
            </div>
      
        <?php echo $this->inlineScript() ?>
    </body>
</html>
