<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        
       
        <?php echo $this->headTitle('Get '. $this->translate('Prescription'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/TablesStyle/demo.css'))
                        ->prependStylesheet($this->basePath('css/TablesStyle/shCore.css'))
                        ->prependStylesheet($this->basePath('css/TablesStyle/jquery.dataTables.css'))
                       
                        

        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
        
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            //->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/demo.js'))
            ->prependFile($this->basePath('js/shCore.js'))
            ->prependFile($this->basePath('js/jquery.dataTables.js'))
            ->prependFile($this->basePath('js/jquery.js'))
           
            
            
           // , 'text/javascript', array('conditional' => 'lt IE 9',))
           // ->prependFile($this->basePath('js/jquery.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
           
            
        ; ?>
        <script type="text/javascript" class="init">
         jQuery(document).ready(function() {
            jQuery('#example').DataTable();
        } );
       </script>
      
    </head>
    <body>
        <nav  id="primary_nav_wrap" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/getpresclogo.png') ?>" alt="Get Prescription"/>&nbsp;</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li class="active"><a href="#"><?php echo $this->translate('Patient') ?></a>
                         <ul><li ><a href="<?php echo $this->url('client/index3', array('controller' => 'auth','action'=>'login')) ;?>"><?php echo $this->translate('Log in') ?></a></li>
                          <li ><a href="<?php echo $this->url('client/index3', array('controller' => 'index','action'=>'detail')) ;?>"><?php echo $this->translate('Register') ?></a></li>
                            <li ><a href="<?php echo $this->url('client/index3', array('controller' => 'index','action'=>'createprofile')) ;?>"><?php echo $this->translate('Edit your profile') ?></a></li>
                          <li ><a href="<?php echo $this->url('client/index3', array('controller' => 'index','action'=>'viewprofile')) ;?>"><?php echo $this->translate('View Profile') ?></a></li>
                         </ul>
                         </li>
                         
                        <li class="active"><a href="#"><?php echo $this->translate('Doctor') ?></a> 
                        <ul><li><a href="<?php echo $this->url('doctor/index1', array('controller' => 'auth','action'=>'login')) ;?>"><?php echo $this->translate('Log in') ?></a></li>
                          <li ><a href="<?php echo $this->url('doctor/index1', array('controller' => 'index','action'=>'detail')) ;?>"><?php echo $this->translate('Register') ?></a></li>
                            <li ><a href="<?php echo $this->url('doctor/index1', array('controller' => 'index','action'=>'seepatients')) ;?>"><?php echo $this->translate('View your patients') ?></a></li>
                          <li ><a href="<?php echo $this->url('doctor/index1', array('controller' => 'recipe','action'=>'createprescription')) ;?>"><?php echo $this->translate('Give prescription') ?></a></li>
                         </ul>
                        </li>
                        <li class="active"><a href="#"><?php echo $this->translate('Pharmacy') ?></a>
                        <ul><li><a href="<?php echo $this->url('pharmacy/index2', array('controller' => 'auth','action'=>'login')) ;?>"><?php echo $this->translate('Log in') ?></a></li>
                          <li ><a href="<?php echo $this->url('pharmacy/index2', array('controller' => 'index','action'=>'detail')) ;?>"><?php echo $this->translate('Register') ?></a></li>
                           <li ><a href="<?php echo $this->url('pharmacy/index2', array('controller' => 'index','action'=>'addmeds')) ;?>"><?php echo $this->translate('Add meds') ?></a></li>
                            <li ><a href="<?php echo $this->url('pharmacy/index2', array('controller' => 'index','action'=>'viewmeds')) ;?>"><?php echo $this->translate('View your meds') ?></a></li>
                          
                         </ul>
                         </li>
                        <li class="active"><a href="<?php echo $this->url('client/index3', array('controller' => 'index','action'=>'findmeds')) ;?>"><?php echo $this->translate('Find medicine') ?></a> </li>
                        <li class="active"><a href="<?php echo $this->url('home') ;?>"><?php echo $this->translate('About') ?></a> </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
              </div> <!-- /container -->
           
            <div>
            <footer>
               
            </footer>
            </div>
      
        <?php echo $this->inlineScript() ?>
    </body>
</html>
