<?php
$title = 'Prescriptions';
 $this->headTitle($title);
 ?>

 <div class="page-header" role="navigation">
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 </div>
 <?php $i = 0;?>
  <?php foreach ($prescriptions as $p) : ?>
 <table class="display" >
 <h2><?php $i++; echo "Prescription No." ." " . $i; ?></h2>
 <h4><?php echo "Diagnostic:". " " .$p->getDiagnostic();?></h4>
 <thead> 
 <tr>
     <th>Drug Name</th>
     

 </tr>
 </thead>
 <tbody>


  <?php 
       $drugs = $p->getDrugs();
       foreach($drugs as $drug):
?>
 <tr>
     <td><?php echo $this->escapeHtml($drug->getName());?> </td>
         
</tr>


   <?php endforeach; ?>
  <?php endforeach; ?>
  </tbody>
 </table>

 </body>